Parameters:
  DataTableName:
    Type: String
    Description: The name of the DynamoDB table where the data is stored.
    Default: DataTable

Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      DeletionProtectionEnabled: True
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TableName: !Ref DataTableName
