IMAGE_SIZE = (150,150)

CLASSES =   [
            'Apple Black Rot',
            'Apple Cedar Rust',
            'Apple Healthy',
            'Apple Scab',
            'Blueberry Healthy',
            'Cherry Powdery Mildew',
            'Cherry Healthy',
            'Corn Cerscopora Gray Leaf Spot',
            'Corn Common Rust',
            'Corn Northern Leaf Blight',
            'Corn Healthy',
            'Grape Black Rot',
            'Grape Esca Black Measles',
            'Grape Isariopsis Leaf Spot',
            'Grape Healthy',
            'Orange Huanglongbing',
            'Peach Bacterial Spot',
            'Peach Healthy',
            'Bell Pepper Bacterial Spot',
            'Bell Pepper Healthy',
            'Potato Early Blight',
            'Potato Late Blight',
            'Potato Healthy',
            'Raspberry Healthy',
            'Soybean Healthy',
            'Squash Powdery Mildew',
            'Strawberry Leaf Scorch',
            'Strawberry Healthy',
            'Tomato Bacterial Spot',
            'Tomato Early Blight',
            'Tomato Late Blight',
            'Tomato Leaf Mold',
            'Tomato Septoria Leaf Spot',
            'Tomato Target Spot',
            'Tomato Spider Mites',
            'Tomato Yellow Leaf Curl',
            'Tomato Healthy',
            'Tomato Mosaic Virus'
            ]
